#!/bin/bash
shopt -s extglob

if [ ! -d "build" ]; then
	./cfg-all
fi

./install-sdl2
./install-audiality2
./install-demo-data
./install-full-data
./install-win32-redist

if [ $# -eq 0 ]; then
	FILTER=@(*release|*demo)
else
	FILTER=$1
fi

SOURCEDIR="$(pwd)"
BUILDDIR="${SOURCEDIR}/build"
PKGDIR="$(pwd)/packages"

if [ ! -d "${PKGDIR}" ]; then
	mkdir "${PKGDIR}"
else
	rm -rf "${PKGDIR}/*"
fi

for i in $BUILDDIR/$FILTER ; do
	echo
	echo "[ Building $(basename $i) ]"
	echo $i
	cd $i
	make -j20
	make package
	mv *.@(rpm|deb|tar.bz2|zip) "${PKGDIR}"
	echo "[ Leaving $(basename $i) ]"
	echo
done
cd ${SOURCEDIR}

# HAX: Can't get CPack to stop adding those bogus directories...
for a in ${PKGDIR}/KoboRedux-*-win32.zip ; do
	echo $a
	zip -d $a */home/*
done

# HAX: No reliable way of selectively flattening archives with CPack. >:-/
for a in ${PKGDIR}/koboredux-*-Linux.tar.bz2 ; do
	echo $a
	${SOURCEDIR}/fix-linux-bz2-package $a
done
