#!/bin/sh
SOURCEDIR=$(pwd)
BUILDDIR=$SOURCEDIR/build

if [ ! -e $BUILDDIR ]; then
	mkdir $BUILDDIR
fi

# MinGW32 cross build using MXE (http://mxe.cc/)
if [ -z $MXEPATH ]; then
	# This is where Dave keeps his MXE.
	MXEPATH=~/src/mxe
fi

create_build_dir() {
	local dname=$1
	local btype=$2
	local desc=$3
	echo
	echo "=== build/$dname ($btype, $desc) ==="
	if [ ! -e $BUILDDIR/$dname ]; then
		mkdir $BUILDDIR/$dname
	fi
	if [ ! -e $BUILDDIR/$dname/src ]; then
		mkdir $BUILDDIR/$dname/src
	fi
	#cp -r $SOURCEDIR/data $BUILDDIR/$dname/src/data
	if [ ! -e $BUILDDIR/$dname/src/data ]; then
		ln -s $SOURCEDIR/data $BUILDDIR/$dname/src/data
	fi
	cd $BUILDDIR/$dname
}

setup_native() {
	local dname=$1
	local btype=$2
	local desc=$3
	local prefix=$4
	local opts="$5"
	create_build_dir $dname $btype $desc
	cmake $opts $SOURCEDIR -DCMAKE_INSTALL_PREFIX=$prefix -DCMAKE_BUILD_TYPE="$btype"
	cd $SOURCEDIR
}

setup_cross() {
	local dname=$1
	local btype=$2
	local desc=$3
	local target=$4
	local opts="$5 -DWIN32_ZIP_BUILD=ON"
	create_build_dir $dname $btype $desc
	cmake $opts -DCMAKE_TOOLCHAIN_FILE=$SOURCEDIR/mingw32-cross.cmake $SOURCEDIR -DCMAKE_BUILD_TYPE="$btype" -DCMAKE_TOOLCHAIN_FILE=$MXEPATH/usr/$target/share/cmake/mxe-conf.cmake -DBUILD_SHARED_LIBS=ON
	cd $SOURCEDIR
}


echo
echo "=========================================================="
echo "Setting up build directories for native targets..."
echo "=========================================================="

setup_native release Release "host native" /usr
setup_native demo Release "host native DEMO" /usr "-DDEMO_BUILD=ON"
setup_native maintainer Maintainer "host native" /usr
setup_native debug Debug "host native" /usr

echo
echo "=========================================================="
echo "Done!"
echo "=========================================================="


echo
echo -n "Looking for MXE in '$MXEPATH'... "
if [ -e $MXEPATH ]; then
	echo "Found!"
	echo
	echo "=========================================================="
	echo "Setting up build directories for MXE cross-compiling..."
	echo "=========================================================="

	setup_cross mingw-release Release "MXE cross" i686-w64-mingw32.shared
	setup_cross mingw-demo Release "MXE cross DEMO" i686-w64-mingw32.shared "-DDEMO_BUILD=ON"
	setup_cross mingw-debug Debug "MXE cross" i686-w64-mingw32.shared

	echo
	echo "=========================================================="
	echo "Done!"
	echo "=========================================================="
else
	echo "Not found!"
	echo "(Please install MXE and set MXEPATH to cross-compile!)"
fi

echo
