#!/bin/bash
SOURCEDIR="$(pwd)"
PKGPATH=$1
ARCHNAME=$(basename ${PKGPATH%})
PKGNAME=${ARCHNAME%.*.*}
[[ ${PKGNAME} == *"demo"* ]] && DEMO="-demo" || DEMO=""

cd $(dirname ${PKGPATH})

echo "Flattening package ${PKGNAME}..."

# Extract
tar -xjvf ${ARCHNAME}
rm -f ${ARCHNAME}
mv ${PKGNAME} orig-pkg

# Rebuild
mkdir ${PKGNAME}
mv orig-pkg/usr/bin/kobord${DEMO} ${PKGNAME}
mv orig-pkg/usr/share/koboredux${DEMO}/* ${PKGNAME}
mv orig-pkg/usr/share/doc/koboredux${DEMO}/* ${PKGNAME}
if [[ ${DEMO} == "" ]] ; then
	cp ${SOURCEDIR}/linux-bundle/.itch.toml ${PKGNAME}
else
	cp ${SOURCEDIR}/linux-bundle/demo.itch.toml ${PKGNAME}/.itch.toml
fi
cp ${SOURCEDIR}/linux-bundle/kobord${DEMO}.sh ${PKGNAME}
cp ${SOURCEDIR}/linux-bundle/koboredux${DEMO}.desktop ${PKGNAME}
mkdir ${PKGNAME}/lib
cp ${SOURCEDIR}/linux-bundle-lib/* ${PKGNAME}/lib

# Archive
BZIP2=--best tar -cvjSf ${ARCHNAME} ${PKGNAME}

# Clean up
rm -rf ${PKGNAME}
rm -rf orig-pkg

echo "Package ${PKGNAME} flattened!"
