#!/bin/sh
. ./BUILDDEFS

set -ex

DEMOARC="KoboRedux-Demo-${DEMO_DATA_RELEASE}-Data.tar.bz2"

if [ ! -d "${WORKDIR}" ]; then
	mkdir "${WORKDIR}"
fi
cd ${WORKDIR}

if [ -d "demo-data" ]; then
	echo "Demo data files (demo-data) already in place!"
	exit
fi

mkdir demo-data
cd demo-data
wget "${KRHOME}/download/${DEMOARC}"
tar -xjvf ${DEMOARC} --strip-components=1
rm ${DEMOARC}
