#!/bin/sh
#
# This script checks out and prepares the full version Kobo Redux data files.
# (Of course, this will not work without access to the private repository.)
#
. ./BUILDDEFS

set -ex

render=false

# Clone or update repository as needed
if [ ! -d "${DLDIR}" ]; then
	mkdir -p "${DLDIR}"
fi
cd ${DLDIR}
if [ ! -d "koboreduxassets" ]; then
	git clone git@github.com:olofson/koboreduxassets.git
	cd koboreduxassets
	git checkout v${KRRELEASE}
	render=true
else
	cd koboreduxassets
	if ! git checkout v${KRRELEASE} ; then
		git checkout master
		git pull
		git checkout v${KRRELEASE}
		render=true
	fi
fi

# Render the TIPE sprites
if "$render" == true || [ ! -f "data/gfx/redux/sprites/bigship.png" ]; then
	cd src
	eel render-sprites
	cd ..
fi

# Make sure we have a link to the actual data directories
if [ ! -d "${WORKDIR}" ]; then
	mkdir "${WORKDIR}"
fi
cd ${WORKDIR}
if [ ! -L "${WORKDIR}/full-data" ]; then
	ln -s "${DLDIR}/koboreduxassets/data" "${WORKDIR}/full-data"
fi
