#!/bin/sh
. ./PACKAGEDEFS

set -ex

render=false

# Clone or update repository as needed
if [ ! -d "koboreduxassets" ]; then
	git clone git@github.com:olofson/koboreduxassets.git
	cd koboreduxassets
	git checkout v${KRRELEASE}
	render=true
else
	cd koboreduxassets
	if ! git checkout v${KRRELEASE} ; then
		git checkout master
		git pull
		git checkout v${KRRELEASE}
		render=true
	fi
fi

# Render the TIPE sprites
if "$render" == true || [ ! -f "data/gfx/redux/sprites/bigship.png" ]; then
	cd src
	eel render-sprites
	cd ..
fi

# Make sure we have a link to the actual data directories
cd ..
if [ ! -L full-data ]; then
	ln -s koboreduxassets/data full-data
fi
