#!/bin/sh

#-------------------
# --- Kobo Redux ---
#-------------------

# Current Kobo Redux release
KRRELEASE=0.7.2

# Kobo Redux source git repository
KRREPO="https://github.com/olofson/koboredux"

# Official Kobo Redux home site (with downloads directory)
KRHOME="http://koboredux.com"

# Archive with Win32 SDL2 redistributables suitable for this release
REDISTARCH="koboredux-libs-redist-win32.tar.bz2"


#--------------------
# --- Audiality 2 ---
#--------------------

# Recommended Audiality 2 version for this Kobo Redux release
A2RELEASE=1.9.2

# Audiality 2 git repository
A2REPO="https://github.com/olofson/audiality2"
